### ISSUE TITLE
Controller updates

### ISSUE THREAD

**Issue by pdarragh** [pdarragh/Spritening#37]
Various things needed in the controller `mainwindow`:
- [x] rename method `iGotClicked`
- [x] implement `getCellAddressFromPointInView`
- [x] implement `getViewPositionFromCellAddress`
- [x] update constructor accordingly, namely
  - [x] define default frame size
  - [x] define optimum view size

**Comment by pdarragh** [comment]
Implementation of `getCellAddressFromPointInView` and `getViewPositionFromCellAddress` taken care of in #46.

**Comment by grzuber** [comment]
Renaming of iGotClicked taken care of in #50

**Comment by grahamhz** [comment]
constructor being worked on in #51

**Comment by grzuber** [comment]
Constructor Updated in #52
